config/routes.rb
Rails.application.routes.draw do
  resources :bank_accounts, only: [:new, :create, :index, :show]
  devise_for :users,
    controllers: { registrations: 'registrations' }
  resources :money_transfers, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :user

  validates :iban, presence: true, length: { maximum: 34 }
  validates :currency, presence: true
end

app/models/money_transfer.rb
class MoneyTransfer < ApplicationRecord
  validates :iban, presence: true
  validates :amount, presence: true
  validates :currency, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bank_accounts, dependent: :destroy

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true, length: { in: 2..30 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  def new
    @bank_account = BankAccount.new
  end

  def create
    @bank_account = current_user.bank_accounts.new(bank_account_params)

    if @bank_account.save
      flash[:success] = 'Account successfully created.'
      redirect_to(@bank_account)
    else
      flash[:error] = @bank_account.errors.full_messages.to_sentence
      render :new
    end
  end

  def index
    @bank_accounts = BankAccount.all
  end

  def show
    @bank_account = BankAccount.find(params[:id])
  end

  private

  def bank_account_params
    params.require(:bank_account).permit(:iban, :balance, :currency)
  end
end

app/controllers/money_transfers_controller.rb
class MoneyTransfersController < ApplicationController
  def new
    @money_transfer = MoneyTransfer.new
  end

  def create
    # TODO: SO with transaction
  end

  private

  def money_transfer_params
    params.require(:bank_account).permit(:iban, :amount, :currency)
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bank_accounts/index.html.erb
Dear, <%= current_user.name %>, your account:
<br>
<table>
  <tr>
    <th>Iban</th>
    <th>Currency</th>
    <th>Balance</th>
    <th>Show</th>
  </tr>
  <tr>
    <% @bank_accounts.each do |account| %>
      <td><%= account.iban %></td>
      <td><%= account.currency %></td>
      <td><%= account.balance %></td>
      <td><%= link_to 'Show', bank_account_path(account) %></td>
    <% end %>
  </tr>
</table>

app/views/bank_accounts/new.html.erb
<%= form_with model: @bank_account do |bank_account| %>
  <%= bank_account.label :iban%>
  <%= bank_account.text_field :iban %><br />

  <%= bank_account.label :currency %>
  <%= bank_account.text_field :currency %><br />

  <% bank_account.label :balane %>
  <% bank_account.text_field :balance %><br />

  <%= bank_account.submit %>
<% end %>

app/views/bank_accounts/show.html.erb
Iban: <%= @bank_account.iban %><br>
Balance: <%= @bank_account.balance %><br>
Currency: <%= @bank_account.currency %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bankowo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/money_transfers/new.html.erb
Transfer:
<%= form_with model: @money_transfer do |t| %>

<%= t.label :iban %>
<%= t.text_field :iban%>

<%= t.label :amount %>
<%= t.text_field :amount %>

<%= t.label :currency %>
<%= t.text_field :currency %>

<%= t.submit %>

<% end %>